### ISSUE TITLE
nim v0.19 string nil issue

### ISSUE THREAD

**Issue by jorisbontje** [nim-lang/redis#14]
With nim v0.19.0:

```
➜  redis git:(master) nimble test
  Executing task test in /Users/user/Projects/nim/redis/redis.nimble
../src/redis.nim(149, 61) template/generic instantiation from here
../src/redis.nim(151, 12) Error: type mismatch: got <nil> but expected 'string'
stack trace: (most recent call last)
/Users/user/Projects/nim/redis/redis.nimble(18) testTask
/Users/user/.choosenim/toolchains/nim-0.19.0/lib/system/nimscript.nim(237) exec
/Users/user/.choosenim/toolchains/nim-0.19.0/lib/system/nimscript.nim(237, 7) Error: unhandled exception: FAILED: nim c -r tests/main.nim
```

My understanding is that this might already be addressed by PR #10

**Comment by dom96** [comment]
Yeah, #10 has some outstanding things that need to be done though.

As a workaround you can compile with ``--laxStrings:on``.

**Comment by Araq** [comment]
It's ``--nilseqs:on``.

**Comment by dom96** [comment]
Ahh yes. Sorry, my bad.

**Comment by sinkingsugar** [comment]
Any update? 
It seems that there is no working solution for Nim to use redis properly right now. 
https://github.com/xmonader/nim-redisclient crashes the compiler even!

nilseqs is not an option all my code is aware of not nil seqs and strings...
:cry:

**Comment by dom96** [comment]
@sinkingsugar not much we can do except get #10 in shape. If you could help out that would be great :)

**Comment by dom96** [comment]
Should be fixed now.
