### ISSUE TITLE
[Question] Does this support RedisJSON?

### ISSUE THREAD

**Issue by ITwrx** [nim-lang/redis#23]
does this client allow one to use the RedisJSON module?

https://github.com/RedisJSON/RedisJSON

thanks

**Comment by Araq** [comment]
I don't know. Try it?

**Comment by ITwrx** [comment]
:) ok, thanks. i thought of that after i posted. I guess i could have closed this issue at that point, but i'm evaluating various solutions and was being lazy about trying each to see how they work and what the capabilities are. Also, I thought an answer might document it for me and others. If i test it and it works i will leave a comment.
