### ISSUE TITLE
Needs version bump

### ISSUE THREAD

**Issue by ftsf** [nim-lang/redis#27]
The current version 0.3.0 is quite broken (eg #24), but there are plenty of fixes since, it would be good to bump the version so `nimble install redis` gives a non broken version.

**Comment by dom96** [comment]
@ftsf I gave you write access to the repo, since you're working in this code base would appreciate your help with fixing the small nits :)

**Comment by ThomasTJdev** [comment]
Is it time for a new tag? Please :relaxed:

**Comment by xflywind** [comment]
see also https://github.com/nim-lang/redis/pull/32

**Comment by xflywind** [comment]
Here is the new release => https://github.com/nim-lang/redis/releases/tag/v0.4.0
