### ISSUE TITLE
Can't compile Redis module

### ISSUE THREAD

**Issue by diegogub** [nim-lang/redis#5]
Hello,

trying to compile it gives following error:

redis.nim(269, 57) template/generic instantiation from here
redis.nim(278, 21) Error: invalid control flow: 'yield' within a constructor

**Comment by yglukhov** [comment]
This feature was disabled some time ago, it should be reenabled with this pr: https://github.com/nim-lang/Nim/pull/7704. Until then you can just move `await` out of seq constructor.

**Comment by diegogub** [comment]
@yglukhov thanks

**Comment by euantorano** [comment]
Interesting. I was able to run the tests when I last worked on this module, though that was just under a year ago now. Thanks for clearing it up @yglukhov!

**Comment by 50hz** [comment]
hi there, I tried to move the "await" out of the seq constructor but get the following error instead? 

/home/hzhao/.nimble/pkgs/redis-0.2.0/redis.nim(278, 13) Error: type mismatch: got <seq[Future[system.string]]> but expected 'seq[string]
